 export const EmployeeActionType = {
  FETCH_EMPLOYEES: 'FETCH_COMPANIES',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_COMPANIES_SUCCESS',
  FETCH_EMPLOYEES_FAIL: 'FETCH_COMPANIES_FAIL',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  UPDATE_EMPLOYEE_SUCCESS: 'UPDATE_EMPLOYEE_SUCCESS',
  UPDATE_EMPLOYEE_FAIL: 'UPDATE_EMPLOYEE_FAIL',
}

