--liquibase formatted sql
--changeset admin:init-tables splitStatements:true endDelimiter:GO


USE [TIMEKEEPING]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERS](
    [EMPLOYEE_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [NAME] [nvarchar](30) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [SHOTENED_NAME] [nvarchar](10) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [USERNAME] [nvarchar](30) NOT NULL,
    [PASSWORD] [nvarchar](250) NOT NULL,
    [WORK_PLACE_ID] int NOT NULL,
    [ROLE] [nvarchar](10) NOT NULL,
    [AUTHENTICATION_FAILURE] INT NULL,
    [EMAIL] [nvarchar](50) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [NOTE] [nvarchar](50) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [PHONE_NUMBER] [nvarchar](11) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [BIRTHDAY] [datetime] NOT NULL,
    [SEX] [nvarchar](10) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [COUNTRY] [nvarchar](20) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [ADDRESS] [nvarchar](20) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [POST_CODE] [nvarchar](7) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [CREATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [CREATED_DT] [datetime] NULL,
    [UPDATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [UPDATED_DT] [datetime] NULL,
    [DELETED_FG] [tinyint] NULL,
    PRIMARY KEY CLUSTERED
        (
            [EMPLOYEE_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
GO

CREATE TABLE [dbo].[QR_CODES](
    [QR_CODE_ID] int NOT NULL IDENTITY(1, 1),
    [QR_CODE] [nvarchar](20) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [EMPLOYEE_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [CREATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [CREATED_DT] [datetime] NULL,
    [UPDATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [UPDATED_DT] [datetime] NULL,
    [DELETED_FG] [tinyint] NULL,
    PRIMARY KEY CLUSTERED
        (
        [QR_CODE_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
GO

CREATE TABLE [dbo].[MST_WORKTIMES](
    [WORKTIME_ID] int NOT NULL IDENTITY(1, 1),
    [START_TIME] [time] NOT NULL,
    [END_TIME] [time] NOT NULL,
    [REST_START_TIME] [time] NULL,
    [REST_END_TIME] [time] NULL,
    [START_BEFORE] INT DEFAULT 0,
    [CREATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [CREATED_DT] [datetime] NULL,
    [UPDATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [UPDATED_DT] [datetime] NULL,
    [DELETED_FG] [tinyint] NULL,
    PRIMARY KEY CLUSTERED
        (
            [WORKTIME_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
GO

CREATE TABLE [dbo].[WORK_PLACES](
    [WORK_PLACE_ID] int NOT NULL IDENTITY(1, 1),
    [NAME] [nvarchar](30) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [PARENT_WORK_PLACE_ID] int NULL,
    [WORKTIME_ID] int NOT NULL,
    [CREATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [CREATED_DT] [datetime] NULL,
    [UPDATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [UPDATED_DT] [datetime] NULL,
    [DELETED_FG] [tinyint] NULL,
    PRIMARY KEY CLUSTERED
        (
            [WORK_PLACE_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
GO

CREATE TABLE [dbo].[WORKDAYS](
    [WORKDAY_ID] int NOT NULL IDENTITY(1, 1),
    [WORK_PLACE_ID] int NOT NULL,
    [WORKDAY] [datetime] NOT NULL,
    [OPENING_TIME] [time] NOT NULL,
    [CLOSING_TIME] [time] NULL,
    [REST_START_TIME] [time] NULL,
    [REST_END_TIME] [time] NULL,
    [START_BEFORE] INT DEFAULT 0,
    [HEADCOUNT] INT DEFAULT 0,
    [CREATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [CREATED_DT] [datetime] NULL,
    [UPDATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [UPDATED_DT] [datetime] NULL,
    PRIMARY KEY CLUSTERED
        (
            [WORKDAY_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
GO

CREATE TABLE [dbo].[WORKDAY_DETAILS](
    [WORKDAY_DETAIL_ID] int NOT NULL IDENTITY(1, 1),
    [WORKDAY_ID] int NOT NULL,
    [EMPLOYEE_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NOT NULL,
    [NOTE] [nvarchar](50) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [CREATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [CREATED_DT] [datetime] NULL,
    [UPDATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [UPDATED_DT] [datetime] NULL,
    PRIMARY KEY CLUSTERED
        (
            [WORKDAY_DETAIL_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
GO

CREATE TABLE [dbo].[WORK_RECORDS](
    [WORK_RECORD_ID] int NOT NULL IDENTITY(1, 1),
    [WORKDAY_DETAIL_ID] int NOT NULL,
    [WORK_PLACE_ID] int NULL,
    [WORK_START_TIME_MORNING] [time] NULL,
    [WORK_END_TIME_MORNING] [time] NULL,
    [WORK_START_TIME_AFTERNOON] [time] NULL,
    [WORK_END_TIME_AFTERNOON] [time] NULL,
    [ABSENTED] [tinyint] NULL,
    [NOTE] [nvarchar](50) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [CREATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [CREATED_DT] [datetime] NULL,
    [UPDATED_ID] [nvarchar](9) COLLATE LATIN1_GENERAL_100_CS_AS_SC_UTF8 NULL,
    [UPDATED_DT] [datetime] NULL,
    PRIMARY KEY CLUSTERED
        (
            [WORK_RECORD_ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
GO



