--liquibase formatted sql
--changeset admin:init-tables splitStatements:true endDelimiter:GO

USE [TIMEKEEPING]
GO
SET IDENTITY_INSERT [dbo].[MST_WORKTIMES] ON

INSERT [dbo].[MST_WORKTIMES] ([WORKTIME_ID], [START_TIME], [END_TIME], [REST_START_TIME], [REST_END_TIME], [START_BEFORE], [CREATED_ID], [CREATED_DT], [UPDATED_ID], [UPDATED_DT], [DELETED_FG]) VALUES (1, CAST(N'09:00:00' AS Time), CAST(N'18:00:00' AS Time), CAST(N'12:00:00' AS Time), CAST(N'13:00:00' AS Time), 5, NULL, NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[MST_WORKTIMES] OFF
GO
INSERT [dbo].[USERS] ([EMPLOYEE_ID], [NAME], [SHOTENED_NAME], [USERNAME], [PASSWORD], [WORK_PLACE_ID], [ROLE], [AUTHENTICATION_FAILURE], [EMAIL], [NOTE], [PHONE_NUMBER], [BIRTHDAY], [SEX], [COUNTRY], [ADDRESS], [POST_CODE], [CREATED_ID], [CREATED_DT], [UPDATED_ID], [UPDATED_DT], [DELETED_FG]) VALUES (N'NV0001347', N'Trần Quang Minh', N'Minh', N'minhtq2@rikkeisoft.com', N'$2a$10$kzn9/chHAQLsePn1dSdZ/udQi4ZG4cyW8zizR3CrxE2eUiEIJJ2Re', N'1', N'Admin', NULL, N'minhtq2@rikkeisoft.com', NULL, N'0123333333', CAST(N'1998-11-27T00:00:00.000' AS DateTime), N'male', N'VietNam', N'Bacninh', N'01', NULL, NULL, NULL, NULL, 0)
GO
SET IDENTITY_INSERT [dbo].[WORK_PLACES] ON

INSERT [dbo].[WORK_PLACES] ([WORK_PLACE_ID], [NAME], [PARENT_WORK_PLACE_ID], [WORKTIME_ID], [CREATED_ID], [CREATED_DT], [UPDATED_ID], [UPDATED_DT], [DELETED_FG]) VALUES (1, N'Rikkei Fukuoka', NULL, 1, NULL, NULL, NULL, NULL, 0)
SET IDENTITY_INSERT [dbo].[WORK_PLACES] OFF
GO




